"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import tempfile
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

from .env import env, env_bool, env_bytes_b64url  # noqa: E402

DEBUG = env("DEBUG", "false").lower() == "true"

SUBSCRIPTIONS_ENABLED: bool = env_bool("FILEPROXY_SUBSCRIPTIONS_ENABLED", default=False)
REGISTRATION_ENABLED: bool = env_bool("FILEPROXY_REGISTRATION_ENABLED", default=True)
BETA_ENABLED: bool = env_bool("FILEPROXY_BETA_ENABLED", default=False)

VAULT_MASTER_KEY = env_bytes_b64url(
    "FILEPROXY_VAULT_MASTER_KEY",
    required=True,
    expected_len=32,
)

GOOGLE_CLIENT_ID = env("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = env("GOOGLE_CLIENT_SECRET")

DROPBOX_APP_KEY = env("DROPBOX_APP_KEY", default="")
DROPBOX_APP_SECRET = env("DROPBOX_APP_SECRET", default="")

# Celery — async background task processing
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_TASK_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_RESULT_BACKEND = None  # State is tracked in PendingUpload model

from celery.schedules import crontab  # noqa: E402

CELERY_BEAT_SCHEDULE = {
    "refresh-all-oauth2-connections": {
        "task": "connections.refresh_all_oauth2_connections",
        "schedule": crontab(minute=0, hour="*/12"),  # 00:00 and 12:00 UTC
    },
}

# Write cache — buffer large uploads to local disk before sending to backend
WRITE_CACHE_DIR = env(
    "WRITE_CACHE_DIR",
    default=os.path.join(tempfile.gettempdir(), "fileproxy", "write_cache"),
)
WRITE_CACHE_THRESHOLD_BYTES = int(env("WRITE_CACHE_THRESHOLD_BYTES", default="1048576"))
# Minutes before an UPLOADING record with no claimed_at update is considered stale.
# Must be greater than the longest expected backend write for a single file.
WRITE_CACHE_STALE_UPLOAD_MINUTES = int(env("WRITE_CACHE_STALE_UPLOAD_MINUTES", default="10"))
# Age in days after which terminal (DONE/CANCELLED/FAILED) PendingUpload rows and
# associated temp files are eligible for deletion by cleanup_pending_uploads.
WRITE_CACHE_CLEANUP_DAYS = int(env("WRITE_CACHE_CLEANUP_DAYS", default="7"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY", "django-insecure-dev-only")

ALLOWED_HOSTS = env("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if DEBUG else ["*"]
CSRF_TRUSTED_ORIGINS = [h for h in env("CSRF_TRUSTED_ORIGINS", "").split(",") if h]

X_FRAME_OPTIONS = "SAMEORIGIN"

# Session cookie security — always enforce HttpOnly and SameSite; only
# enforce Secure in production (DEBUG=False) so local dev still works.
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# HTTPS enforcement in production
SECURE_SSL_REDIRECT = not DEBUG
SECURE_REDIRECT_EXEMPT = [r"^health/"]  # ALB health check hits port 8000 over HTTP
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")  # Trust ALB's forwarded proto
SECURE_HSTS_SECONDS = 0 if DEBUG else 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/home/"
LOGOUT_REDIRECT_URL = "/accounts/login/"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "core.apps.CoreConfig",
    "connections.apps.ConnectionsConfig",
    "files.apps.FilesConfig",
    "api.apps.ApiConfig",
    "accounts.apps.AccountsConfig",
    "usage.apps.UsageConfig",
    "subscription.apps.SubscriptionConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "accounts.authentication.APIKeyAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
}

SIMPLE_JWT = {
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "FileProxy API",
    "DESCRIPTION": "API documentation",
    "VERSION": "1.0.0",
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
}


ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "config.context_processors.subscription_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Allow large file uploads via multipart write endpoint.
# Override with DATA_UPLOAD_MAX_MEMORY_SIZE env var (bytes). Default: 500 MB.
DATA_UPLOAD_MAX_MEMORY_SIZE = int(env("DATA_UPLOAD_MAX_MEMORY_SIZE", str(500 * 1024 * 1024)))
FILE_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024  # 2 MB — spill file data to disk early


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_db_host = env("DB_HOST", "")
if _db_host:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env("DB_NAME", "fileproxy"),
            "USER": env("DB_USER", "fileproxy"),
            "PASSWORD": env("DB_PASSWORD", ""),
            "HOST": _db_host,
            "PORT": env("DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = env("STATIC_URL", "/static/")
STATIC_ROOT = BASE_DIR / "staticfiles"
# In development, serve files directly so TS rebuilds are reflected without collectstatic.
# In production, use content-hashed filenames for aggressive caching.
# NOTE: STATICFILES_STORAGE was removed in Django 6.0; use STORAGES instead.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
