# Generated by Django 6.0.1 on 2026-02-26 03:01

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('aws_s3', 'AWS S3 Credentials'), ('gdrive_oauth2', 'Google Drive (OAuth 2.0)'), ('dropbox_oauth2', 'Dropbox (OAuth 2.0)'), ('azure_blob', 'Azure Blob Storage')], max_length=32)),
                ('wrapped_dek', models.TextField()),
                ('payload_nonce', models.CharField(max_length=32)),
                ('payload_ciphertext', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['scope', 'kind'], name='connections_scope_ac094a_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'name'), name='uniq_connection_scope_name')],
            },
        ),
    ]
