# Generated by Django 6.0.1 on 2026-02-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(db_index=True, max_length=200)),
                ('vault_item_name', models.CharField(max_length=200)),
                ('vault_item_kind', models.CharField(max_length=50)),
                ('operation', models.CharField(choices=[('test', 'Test'), ('enumerate', 'Enumerate'), ('read', 'Read'), ('write', 'Write'), ('delete', 'Delete')], max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('object_path', models.CharField(blank=True, default='', max_length=1000)),
                ('ok', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['scope', 'occurred_at'], name='usage_usage_scope_5796bd_idx')],
            },
        ),
    ]
