# Generated by Django 6.0.1 on 2026-02-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='bytes_transferred',
            field=models.BigIntegerField(default=0),
        ),
    ]
