# Generated by Django 6.0.1 on 2026-03-21 15:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_index=True)),
                ('connection_name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=4096)),
                ('temp_file_path', models.CharField(max_length=4096)),
                ('expected_size', models.BigIntegerField()),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'connection_name', 'path', 'status'], name='files_pendi_user_id_8d6879_idx')],
            },
        ),
    ]
