# Generated by Django 6.0.1 on 2026-03-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_add_claimed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingupload',
            name='claimed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
