# Generated by Django 6.0.1 on 2026-01-26 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VaultItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[("aws_s3", "AWS S3 Credentials")], max_length=32
                    ),
                ),
                ("wrapped_dek", models.TextField()),
                ("payload_nonce", models.CharField(max_length=32)),
                ("payload_ciphertext", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vault_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "kind"], name="vault_vault_user_id_369d11_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "name"), name="uniq_vaultitem_user_name"
                    )
                ],
            },
        ),
    ]
