# Generated by Django 6.0.1 on 2026-02-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VaultItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(choices=[("aws_s3", "AWS S3 Credentials")], max_length=32),
                ),
                ("wrapped_dek", models.TextField()),
                ("payload_nonce", models.CharField(max_length=32)),
                ("payload_ciphertext", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["scope", "kind"], name="vault_vault_scope_1d65bb_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "name"), name="uniq_vaultitem_scope_name"
                    )
                ],
            },
        ),
    ]
