# Generated by Django 6.0.1 on 2026-02-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vault", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaultitem",
            name="kind",
            field=models.CharField(
                choices=[
                    ("aws_s3", "AWS S3 Credentials"),
                    ("gdrive_oauth2", "Google Drive (OAuth 2.0)"),
                    ("dropbox_oauth2", "Dropbox (OAuth 2.0)"),
                ],
                max_length=32,
            ),
        ),
    ]
