# Generated by Django 6.0.1 on 2026-02-22 20:59

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vault", "0002_alter_vaultitem_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaultitem",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
